---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vote-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3-alpine
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: vote
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password

