apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: vote-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: NodePort
  selector:
    app: website
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000 

